"""
Unit tests for ChromaStore.
Uses random unit-norm vectors so no model download is required.
Each test gets an isolated tmp_path Chroma directory via the `store` fixture.
Trivial test. 
"""

import math
import random

import pytest

from glance.store import ChromaStore, Hit, Item

# The dimension of the vector embedding space.
# Matches the dimensions returned by the CLIPEmbedder model (512-dim).
DIM = 512  # matches CLIPEmbedder._DIM


def rand_vec() -> list[float]:
    """
    Generates a random unit-norm vector in a 512-dimensional space.
    This simulates embeddings generated by CLIP or other embedding models without
    needing to load or run the actual machine learning model during tests.
    """
    v = [random.gauss(0, 1) for _ in range(DIM)]
    norm = math.sqrt(sum(x ** 2 for x in v))
    return [x / norm for x in v]


@pytest.fixture
def store(tmp_path):
    """
    A pytest fixture that initializes an isolated ChromaStore instance.
    `tmp_path` is a standard pytest fixture providing a temporary directory unique to each test run,
    ensuring tests do not share state or interfere with each other's database records.
    """
    return ChromaStore(chroma_dir=tmp_path / "chroma")


# --- Group 1: Add + Query Functionality ---

def test_query_exact_match_scores_near_one(store):
    """
    Tests that querying the store with the exact same vector that was added
    returns that item with a similarity score very close to 1.0 (cosine similarity).
    """
    vec = rand_vec()
    store.add("id1", vec, {"path": "/photos/cat.jpg", "type": "image"})
    hits = store.query(vec, k=1)
    
    assert len(hits) == 1
    assert hits[0].path == "/photos/cat.jpg"
    assert hits[0].score > 0.99  # same vector queried back = cosine sim ~1.0


def test_query_returns_best_match_first(store):
    """
    Tests that when querying, the results are ranked by similarity score in descending order,
    ensuring the closest vector match is returned first in the list.
    """
    target = rand_vec()
    noise = rand_vec()
    store.add("id1", target, {"path": "/a.jpg", "type": "image"})
    store.add("id2", noise, {"path": "/b.jpg", "type": "image"})
    
    hits = store.query(target, k=2)
    assert hits[0].path == "/a.jpg"
    assert hits[0].score > hits[1].score


def test_text_chunk_snippet_returned(store):
    """
    Verifies that for items of type 'text', the original source text snippet
    is stored and correctly retrieved inside the Hit object.
    """
    vec = rand_vec()
    store.add("id1", vec, {"path": "/notes.md", "type": "text", "text": "cats are obligate carnivores"})
    hits = store.query(vec, k=1)
    
    assert hits[0].snippet == "cats are obligate carnivores"


def test_image_has_no_snippet(store):
    """
    Verifies that for items of type 'image', no snippet field is returned
    (it should be None since images do not contain textual chunks).
    """
    vec = rand_vec()
    store.add("id1", vec, {"path": "/cat.jpg", "type": "image"})
    hits = store.query(vec, k=1)
    
    assert hits[0].snippet is None


# --- Group 2: Upsert Behavior ---

def test_upsert_overwrites_same_id(store):
    """
    Tests that adding an item with an existing ID updates/overwrites its embedding vector
    and metadata rather than creating a duplicate entry.
    """
    vec1 = rand_vec()
    vec2 = rand_vec()
    store.add("id1", vec1, {"path": "/cat.jpg", "type": "image"})
    store.add("id1", vec2, {"path": "/cat.jpg", "type": "image"})  # same id, new vector
    
    hits = store.query(vec2, k=1)
    assert len(hits) == 1           # still one entry, not two
    assert hits[0].score > 0.99     # matches the updated vec2, not the old vec1


# --- Group 3: Delete Operations ---

def test_delete_removes_all_chunks_for_path(store):
    """
    Tests that delete_by_path deletes all chunks (e.g. text segments or image references)
    associated with a specific document path, leaving other paths untouched.
    """
    vec = rand_vec()
    store.add("chunk0", vec, {"path": "/notes.md", "type": "text", "text": "chunk 0"})
    store.add("chunk1", vec, {"path": "/notes.md", "type": "text", "text": "chunk 1"})
    store.add("other",  vec, {"path": "/other.md", "type": "text", "text": "other"})

    removed = store.delete_by_path("/notes.md")
    assert removed == 2  # two chunks should have been deleted

    remaining = store.list()
    assert len(remaining) == 1
    assert remaining[0].path == "/other.md"


def test_delete_nonexistent_path_returns_zero(store):
    """
    Tests that calling delete_by_path on a path that does not exist safely returns 0,
    representing that 0 records were deleted.
    """
    assert store.delete_by_path("/does/not/exist.md") == 0


# --- Group 4: Listing Items ---

def test_list_deduplicates_chunks_by_path(store):
    """
    Tests that listing items in the store returns a deduplicated view based on file paths.
    Even if a text file has multiple chunks, listing should only return one Item per path.
    """
    vec = rand_vec()
    store.add("c0", vec, {"path": "/notes.md", "type": "text", "text": "chunk 0"})
    store.add("c1", vec, {"path": "/notes.md", "type": "text", "text": "chunk 1"})
    store.add("img", vec, {"path": "/cat.jpg", "type": "image"})

    items = store.list()
    paths = {i.path for i in items}
    assert paths == {"/notes.md", "/cat.jpg"}  # notes.md appears once, not twice


def test_list_type_filter_image(store):
    """
    Verifies that list(type_filter="image") filters the results to only include images.
    """
    vec = rand_vec()
    store.add("img", vec, {"path": "/cat.jpg", "type": "image"})
    store.add("txt", vec, {"path": "/notes.md", "type": "text", "text": "hi"})

    images = store.list(type_filter="image")
    assert len(images) == 1
    assert images[0].type == "image"


def test_list_type_filter_text(store):
    """
    Verifies that list(type_filter="text") filters the results to only include text items.
    """
    vec = rand_vec()
    store.add("img", vec, {"path": "/cat.jpg", "type": "image"})
    store.add("txt", vec, {"path": "/notes.md", "type": "text", "text": "hi"})

    texts = store.list(type_filter="text")
    assert len(texts) == 1
    assert texts[0].type == "text"


# --- Group 5: Counting Items ---

def test_count_by_type(store):
    """
    Verifies that store.count() returns a dictionary with correct counts of items
    grouped by their type ('image' and 'text').
    """
    vec = rand_vec()
    store.add("i1", vec, {"path": "/cat.jpg", "type": "image"})
    store.add("i2", vec, {"path": "/dog.jpg", "type": "image"})
    store.add("t1", vec, {"path": "/notes.md", "type": "text", "text": "hi"})

    counts = store.count()
    assert counts["image"] == 2
    assert counts["text"] == 1


def test_count_empty_store(store):
    """
    Verifies that store.count() on an empty database returns 0 for both 'image' and 'text'.
    """
    counts = store.count()
    assert counts["image"] == 0
    assert counts["text"] == 0

